### ISSUE TITLE
Reason for having date as mandatory property?

### ISSUE THREAD

**Issue by k----n** [AlexJF/pelican-entities#4]
In pelican when generating pages, date is not a mandatory property. Is there any reason why dates are mandatory for entities?

**Comment by AlexJF** [comment]
I based the entity generator on the article generator from pelican core. I guess that I added date as mandatory property at the time due to the period archive generation code and date sorting.

With ed3b2c71, removed it as mandatory (still keeping it as a sane default though) and added a safeguard around the period archive generation. Just make sure to change your SORTER setting to account for entities that may no longer have a date.
